services:
  frontend:
    build: ./pbm_model_interface
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - backend
  
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    environment:
      SQLITE_PATH: /data/pbm.sqlite3
    volumes:
      - pbm_data:/data
    restart: on-failure
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: sh -c "python3 cli.py api"

volumes:
  pbm_data:
